### ISSUE TITLE
Cannot "docker run" commands with arguments inside container

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/docker-arvados-dev#1]
The example in /README.md where run-tests.sh is ran with an argument bound to the WORKSPACE parameter does not work (and not just because the tilde (~) character is incorrectly used).

**Comment by colin-nolan** [comment]
Works as expected:
`docker run debian:jessie echo "Hello World"`

Does not work as expected:
`docker run --privileged local/docker-arvados-dev echo "Hello World"`

**Comment by jrandall** [comment]
Example in README.md fixed to include single quotes that are required when shell metacharacters (such as `~`) are on the command-line. Fixed in e83587914c9ed846addb108b1d315a23b01d768b

**Comment by jrandall** [comment]
Currently testing fix for commands with multiple arguments such as `echo "Hello World"`

**Comment by jrandall** [comment]
Fixed in e0b5d1e86c2aab7f13c9190f2920d46935f21728
